### ISSUE TITLE
关于简历项目的几个问题

### ISSUE THREAD

**Issue by gamedebug** [GaoYumeng/test#1]
你司网站日访问量多大？最高并发能到多少？集群化之后的规模扩大的怎样的规模？能否描述项目整体的拓扑结构？haproxy的ACL具体如何实现？集群是基于原来的web继续搭建还是完全重新搭建？如果重新搭建那么后期的数据迁移怎么做的？谁负责的？是否实现了在线数据迁移？haproxy ACL还能控制权限？我读书少你别骗我！！web后端是否有数据库？web集群化了，那数据库有没有相关的集群方案？从你项目职责第一句话看你所做的都是“实验”，那么真实的生产环境上的搭建和配置是否是你亲手操作的？你司运维团队多少人？如何分工？你负责哪一部分？向谁汇报工作？日常的工作都有什么？

**Comment by GaoYumeng** [comment]
老师收到我会尽快修改

**Comment by gamedebug** [comment]
别说尽快，给我时间节点

**Comment by GaoYumeng** [comment]
周二之前完成

**Comment by gamedebug** [comment]
说好的周二呢？
